
package com.bootcamp.customerserviceplan.registration.service.soapclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T04:00:19.786-05:00
 * Generated source version: 3.1.7
 * 
 */
public final class ElectricityServicePlan_ElectricityServicePlanImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soapws.service.electricityplan.utilityservice.bootcamp.com/", "ElectricServicePlan");

    private ElectricityServicePlan_ElectricityServicePlanImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ElectricServicePlan.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ElectricServicePlan ss = new ElectricServicePlan(wsdlURL, SERVICE_NAME);
        ElectricityServicePlan port = ss.getElectricityServicePlanImplPort();  
        
        {
        System.out.println("Invoking getElectricityServicePlan...");
        java.util.List<com.bootcamp.customerserviceplan.registration.service.soapclient.ServicePlan> _getElectricityServicePlan__return = port.getElectricityServicePlan();
        System.out.println("getElectricityServicePlan.result=" + _getElectricityServicePlan__return);


        }

        System.exit(0);
    }

}
