package com.bootcamp.customerserviceplan.registration.service.soapclient;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T12:52:50.185-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://soapws.service.electricityplan.utilityservice.bootcamp.com/", name = "ElectricityServicePlan")
@XmlSeeAlso({ObjectFactory.class})
public interface ElectricityServicePlan {

    @WebMethod
    @RequestWrapper(localName = "getElectricityServicePlan", targetNamespace = "http://soapws.service.electricityplan.utilityservice.bootcamp.com/", className = "com.bootcamp.customerserviceplan.registration.service.soapclient.GetElectricityServicePlan")
    @ResponseWrapper(localName = "getElectricityServicePlanResponse", targetNamespace = "http://soapws.service.electricityplan.utilityservice.bootcamp.com/", className = "com.bootcamp.customerserviceplan.registration.service.soapclient.GetElectricityServicePlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bootcamp.customerserviceplan.registration.service.soapclient.ServicePlan> getElectricityServicePlan();
}
